### ISSUE TITLE
Trees growin on item ghosts.

### ISSUE THREAD

**Issue by staviq** [NoxyNixie/Noxys_Trees#3] opened 2018-01-14 13:55 UTC
Hi, should check for placed item ghosts when growing new trees.

I had this happen many times until i realized what's going on.

If you place a blueprint, and then say run out of items, you go back to the main base, and return to your placed blueprint, new trees can grow in that area, and bots will not build because the new trees are not marked for deconstruction.

**Comment by NoxyNixie** [comment] 2018-01-14 14:56
Ah yeah that is a good one. I'll have a look at that momentarily and probably have a build in a few hours with that fixed ;)

**Comment by NoxyNixie** [comment] 2018-01-14 15:21
Ok I just tested and trees shouldn't spawn on player build ghost entities because of the `Minimum distance to player entities` setting.

If you changed that to 0 or close to 0 then trees ignoring ghosts should be expected behavior.

The default for that setting is 2 so no trees should get closer than that to an entity.

Even with entities much larger than 2 tiles it still does not on my end clear or grow into ghost entities because factorio is smart and uses bounding boxes to check entities in an area.

**Comment by NoxyNixie** [comment] 2018-01-14 17:09
Closing this as it does not appear to actually be an issue with the right (default) settings:

![](http://cyanox.nl/sc/2018-01-14-18-06-19.png)

**Comment by staviq** [comment] 2018-01-14 22:54
It definitely is still happening for me, and usually with small item ghosts like belts or inserters.

**Comment by NoxyNixie** [comment] 2018-01-14 23:00
Can you tell me your settings and maybe show a screenshot? Or a world download?

**Comment by staviq** [comment] 2018-01-15 20:43
I have tried to reproduce and found that this happens not only with trees but also with rocks.
Does your mod do anything with rocks? Because if it doesn't the problem is elsewhere entirely.

**Comment by NoxyNixie** [comment] 2018-01-15 20:46
Absolutely not. You may have some other mod doing some odd stuff then ;)

**Comment by staviq** [comment] 2018-01-15 21:33
Alright then, sorry for bothering you :)

**Comment by NoxyNixie** [comment] 2018-01-15 21:38
No problem. For future reference did you find out what mod does do it?

**Closed as completed by NoxyNixie** 2018-01-15 21:38 UTC

**Comment by staviq** [comment] 2018-01-15 21:44
Not yet, but there seems to be a problem with factorio forgetting things were marked for deconstruction.

**Comment by staviq** [comment] 2018-01-15 21:57
Quick question, can you tell if a tree was grown by factorio mapgen or by your mod given a game save and no log ?

**Comment by NoxyNixie** [comment] 2018-01-15 22:14
Not easily. Only way I know of is to create a new world with exact same settings but noxys trees disabled and then comparing the two worlds side by side. Vanilla does not spread trees so the initial world creation trees should be identical.

**Comment by staviq** [comment] 2018-01-15 22:14
Ok thanks.
